"""LaTeX tables and result macros generated from audited aggregate data."""

from __future__ import annotations

from pathlib import Path
import re

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "results" / "summary" / "numerical"
TABLES.mkdir(parents=True, exist_ok=True)

SCENARIO_LABELS = {
    "regular_sir_full": "SIR, full observation",
    "early_seir_infected_only": "SEIR, early partial observation",
    "missing_time_varying_transmission": "Time-varying transmission",
    "missing_neural_feedback": "Missing neural feedback",
    "noisy_sir_overfit_risk": "Noisy SIR",
}
METHODS = ("aic", "bic", "gic_eff", "gic_vol_050")
METHOD_LABELS = {"aic": "AIC", "bic": "BIC", "gic_eff": "GIC-eff", "gic_vol_050": "GIC-vol"}
STUDY_LABELS = {
    "biochemical_haldane": "Biochemical: Haldane",
    "biochemical_ude": "Biochemical: UDE",
    "ecology_rm": "Ecology: RM",
    "fhn_standard": "FHN: standard",
    "fhn_ude": "FHN: UDE",
}


def _macro_name(*parts: str) -> str:
    words = re.findall(r"[A-Za-z]+|\d+", " ".join(parts))
    return "Num" + "".join(word[:1].upper() + word[1:] for word in words)


def write_macros() -> None:
    selections = pd.read_csv(TABLES / "core_selections.csv")
    lines = ["% Generated by analysis/tables.py"]
    for (scenario, criterion), group in selections.groupby(["scenario", "criterion"]):
        lines.append(
            f"\\newcommand{{\\{_macro_name(scenario, criterion, 'recovery')}}}{{{group['correct'].mean():.2f}}}"
        )
        lines.append(
            f"\\newcommand{{\\{_macro_name(scenario, criterion, 'n')}}}{{{len(group)}}}"
        )
    diagnostics = pd.read_csv(TABLES / "core_scores.csv")
    lines.append(f"\\newcommand{{\\NumCoreFits}}{{{len(diagnostics)}}}")
    lines.append(f"\\newcommand{{\\NumCoreSeeds}}{{{diagnostics['seed'].nunique()}}}")
    cross_path = TABLES / "crossdomain_selections.csv"
    if cross_path.exists():
        cross = pd.read_csv(cross_path)
        for (study, criterion), group in cross.groupby(["study", "criterion"]):
            lines.append(
                f"\\newcommand{{\\{_macro_name(study, criterion, 'recovery')}}}{{{group['correct'].mean():.2f}}}"
            )
    phase_path = TABLES / "phase_diagram_summary.csv"
    if phase_path.exists():
        phase = pd.read_csv(phase_path)
        gic = phase[phase["criterion"] == "gic_eff"]
        if not gic.empty:
            hardest = gic.sort_values(["n_times", "noise", "trajectories"], ascending=[True, False, True]).iloc[0]
            easiest = gic.sort_values(["n_times", "noise", "trajectories"], ascending=[False, True, False]).iloc[0]
            lines.append(f"\\newcommand{{\\NumPhaseHardRecovery}}{{{hardest['mean']:.2f}}}")
            lines.append(f"\\newcommand{{\\NumPhaseEasyRecovery}}{{{easiest['mean']:.2f}}}")
    predictive_path = TABLES / "predictive_model_averaging_summary.csv"
    if predictive_path.exists():
        predictive = pd.read_csv(predictive_path)
        for _, row in predictive.iterrows():
            lines.append(
                f"\\newcommand{{\\{_macro_name(row['scenario'], row['method'], 'mse')}}}{{{row['mse_mean']:.3g}}}"
            )
    (TABLES / "results_macros.tex").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_core_table() -> None:
    selection = pd.read_csv(TABLES / "core_selections.csv")
    lines = [
        "\\begin{table}[t]", "\\caption{Recovery of the data-generating candidate over independent noise realizations. Entries are rates; Wilson 95\\% intervals are reported in Figure~\\ref{fig:core-recovery}.}",
        "\\label{tab:core-recovery}", "\\centering", "\\begin{tabular}{lcccc}",
        "\\toprule", "Data-generating setting & AIC & BIC & GIC-eff & GIC-vol\\\\", "\\midrule",
    ]
    for scenario, label in SCENARIO_LABELS.items():
        values = []
        subset = selection[selection["scenario"] == scenario]
        for method in METHODS:
            group = subset[subset["criterion"] == method]
            values.append("--" if group.empty else f"{group['correct'].mean():.2f}")
        lines.append(label + " & " + " & ".join(values) + "\\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}"])
    (TABLES / "core_recovery.tex").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_crossdomain_table() -> None:
    path = TABLES / "crossdomain_selections.csv"
    if not path.exists():
        return
    selection = pd.read_csv(path)
    lines = [
        "\\begin{table}[t]", "\\caption{Cross-domain truth-recovery rates. Each row uses paired noise realizations across candidates.}",
        "\\label{tab:crossdomain-recovery}", "\\centering", "\\begin{tabular}{lcccc}",
        "\\toprule", "Study & AIC & BIC & GIC-eff & GIC-vol\\\\", "\\midrule",
    ]
    for study in sorted(selection["study"].unique()):
        values = []
        subset = selection[selection["study"] == study]
        for method in METHODS:
            group = subset[subset["criterion"] == method]
            values.append("--" if group.empty else f"{group['correct'].mean():.2f}")
        lines.append(STUDY_LABELS.get(study, study.replace("_", " ")) + " & " + " & ".join(values) + "\\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}"])
    (TABLES / "crossdomain_recovery.tex").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_scalability_table() -> None:
    path = TABLES / "scalability_summary.csv"
    if not path.exists():
        return
    frame = pd.read_csv(path)
    lines = [
        "\\begin{tabular}{rrrrr}", "\\toprule",
        "$d$ & Jacobian (s) & $J^TJ$ (s) & Spectrum (s) & Tensors (MiB)\\\\",
        "\\midrule",
    ]
    for _, row in frame.iterrows():
        lines.append(
            f"{int(row['dimension'])} & {row['jacobian_median']:.3g} & {row['gram_median']:.3g} & {row['spectrum_median']:.3g} & {row['tensor_megabytes']:.2f}\\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    (TABLES / "scalability_summary.tex").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_confidence_table() -> None:
    path = ROOT / "results" / "summary" / "confidence_coverage_summary.csv"
    if not path.exists():
        return
    frame = pd.read_csv(path)
    frame = frame[frame["nominal"].isin((0.90, 0.95))]
    labels = {
        "naive_wald": "Raw Wald",
        "geometric_quotient": "Quotient Wald",
        "simulation_calibrated": "Simulation calibrated",
    }
    lines = [
        "\\begin{tabular}{lllrr}", "\\toprule",
        "Setting & Method & Nominal & Coverage & 95\\% interval\\\\", "\\midrule",
    ]
    for _, row in frame.sort_values(["scenario", "nominal", "method"]).iterrows():
        setting = SCENARIO_LABELS.get(row["scenario"], row["scenario"].replace("_", " "))
        lines.append(
            f"{setting} & {labels[row['method']]} & {row['nominal']:.2f} & "
            f"{row['coverage']:.3f} & [{row['coverage_ci_low']:.3f}, {row['coverage_ci_high']:.3f}]\\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    (TABLES / "confidence_coverage.tex").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_predictive_table() -> None:
    path = TABLES / "predictive_model_averaging_summary.csv"
    if not path.exists():
        return
    frame = pd.read_csv(path)
    labels = {
        "equal": "Equal", "aic": "AIC weights", "bic": "BIC weights",
        "gic_eff": "GIC-eff weights", "gic_vol_050": "GIC-vol weights",
        "stacking": "Stacking", "hard_gic": "Hard GIC-eff",
    }
    lines = [
        "\\begin{tabular}{llrrrr}", "\\toprule",
        "Setting & Combination & MSE [95\\% CI] & Log score & Coverage & Width\\\\", "\\midrule",
    ]
    for _, row in frame.sort_values(["scenario", "method"]).iterrows():
        setting = SCENARIO_LABELS.get(row["scenario"], row["scenario"].replace("_", " "))
        lines.append(
            f"{setting} & {labels[row['method']]} & {row['mse_mean']:.3g} "
            f"[{row['mse_ci_low']:.3g}, {row['mse_ci_high']:.3g}] & "
            f"{row['log_score_mean']:.3g} & {row['coverage90']:.3f} & {row['width90']:.3g}\\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    (TABLES / "predictive_summary.tex").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_fit_diagnostics_table() -> None:
    path = TABLES / "core_fit_diagnostics.csv"
    if not path.exists():
        return
    frame = pd.read_csv(path)
    summary = frame.groupby("candidate").agg(
        n=("n", "sum"), median_gradient=("median_gradient_norm", "median"),
        median_seconds=("median_wall_seconds", "median"),
    ).reset_index()
    lines = [
        "\\begin{tabular}{lrrr}", "\\toprule",
        "Candidate & Fits & Median gradient norm & Median wall time (s)\\\\", "\\midrule",
    ]
    for _, row in summary.iterrows():
        lines.append(
            f"{row['candidate'].replace('_', ' ')} & {int(row['n'])} & "
            f"{row['median_gradient']:.3g} & {row['median_seconds']:.3g}\\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    (TABLES / "fit_diagnostics.tex").write_text("\n".join(lines) + "\n", encoding="ascii")


def write_crossdomain_fit_diagnostics_table() -> None:
    path = TABLES / "crossdomain_fit_diagnostics.csv"
    if not path.exists():
        return
    frame = pd.read_csv(path).sort_values(["study", "candidate"])
    lines = [
        "\\begin{tabular}{llrrr}", "\\toprule",
        "Study & Candidate & Fits & Median gradient norm & Median time (s)\\\\", "\\midrule",
    ]
    for _, row in frame.iterrows():
        study = STUDY_LABELS.get(row["study"], row["study"].replace("_", " "))
        candidate = row["candidate"].replace("_", " ")
        lines.append(
            f"{study} & {candidate} & {int(row['n'])} & "
            f"{row['median_gradient_norm']:.3g} & {row['median_wall_seconds']:.3g}\\\\"
        )
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    (TABLES / "crossdomain_fit_diagnostics.tex").write_text(
        "\n".join(lines) + "\n", encoding="ascii"
    )


def main() -> None:
    write_macros()
    write_core_table()
    write_crossdomain_table()
    write_scalability_table()
    write_confidence_table()
    write_predictive_table()
    write_fit_diagnostics_table()
    write_crossdomain_fit_diagnostics_table()


if __name__ == "__main__":
    main()


